import type {Route} from './+types/root';
import {I18nextProvider, useTranslation} from 'react-i18next';
import {isRouteErrorResponse, Links, Meta, Outlet, Scripts, ScrollRestoration} from 'react-router';
import {i18n} from './i18n';

import './styles/tailwind.css';
import './styles/main.scss';

export const links: Route.LinksFunction = () => [
  {rel: 'preconnect', href: 'https://fonts.googleapis.com'},
  {rel: 'preconnect', href: 'https://fonts.gstatic.com', crossOrigin: 'anonymous'},
  {
    rel: 'stylesheet',
    href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Lora:ital,wght@0,400;0,500;0,600;1,400&display=swap',
  },
  // Favicon bundle generated by RealFaviconGenerator. Files live in /public.
  {rel: 'icon', type: 'image/png', sizes: '96x96', href: '/favicon-96x96.png'},
  {rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg'},
  {rel: 'shortcut icon', href: '/favicon.ico'},
  {rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png'},
  {rel: 'manifest', href: '/site.webmanifest'},
];

// Runs before React hydrates so the correct theme class is on <body> for the
// first paint — avoids a light/dark flash. Reads localStorage, then
// prefers-color-scheme. Kept as a tight string so it parses fast inline.
// eslint-disable-next-line style/max-len -- inline IIFE intentionally minified to one line for fastest parse before hydration (avoids theme FOUC)
const themeBootstrap = `(function(){try{var k='weleda-konverter:theme';var s=localStorage.getItem(k);var t=(s==='light'||s==='dark')?s:(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');document.body.classList.add(t);}catch(e){document.body.classList.add('light');}})();`;

export function Layout({children}: {children: React.ReactNode}) {
  return (
    // Browser extensions (Grammarly, password managers, dark-mode helpers,
    // …) attach attributes / inline styles to <html> and <body> after the
    // server-rendered HTML lands and before React hydrates. That diff
    // would otherwise log a hydration warning the user can't fix.
    <html lang="de" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="apple-mobile-web-app-title" content="WebCenter Konverter" />
        <meta name="theme-color" content="#5e8c40" media="(prefers-color-scheme: light)" />
        <meta name="theme-color" content="#86bd67" media="(prefers-color-scheme: dark)" />
        <Meta />
        <Links />
      </head>
      <body suppressHydrationWarning>
        {/* eslint-disable-next-line react-dom/no-dangerously-set-innerhtml -- themeBootstrap is a constant string defined above; no user input, no escaping needed */}
        <script dangerouslySetInnerHTML={{__html: themeBootstrap}} />
        <I18nextProvider i18n={i18n}>{children}</I18nextProvider>
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  return <Outlet />;
}

export function ErrorBoundary({error}: Route.ErrorBoundaryProps) {
  const {t} = useTranslation();
  const message = isRouteErrorResponse(error)
    ? `${error.status} ${error.statusText}`
    : error instanceof Error
      ? error.message
      : t('errors.unknown');
  return (
    <main className="fallback-page">
      <h1>{t('errors.generic_title')}</h1>
      <p>{message}</p>
    </main>
  );
}
